#pragma once

#include <array>
#include <cstdint>
#include <map>
#include <string>
#include <tuple>
#include <utility>
#include <vector>

namespace zac_native {

inline constexpr int kNativeAbiVersion = 7;

struct Point {
  double x{};
  double y{};
};

struct Leg {
  double distance_um{};
  Point source;
  Point target;
};

struct Ghost {
  std::int64_t atom{};
  Point position;
};

struct MovementPhase {
  std::vector<Leg> legs;
  std::vector<Ghost> ghosts;
  std::vector<std::int64_t> owners;
  std::string batching{"phase"};
};

struct CandidatePlan {
  std::vector<std::int64_t> chromosome;
  std::vector<MovementPhase> phases;
  std::int64_t idle_exposures{};
};

struct BoundaryConfig {
  std::int64_t seed{};
  std::size_t max_unique_evaluations{};
  std::size_t exact_coloring_threshold{};
  std::string horizon_policy{"fixed"};
  std::size_t max_horizon{};
  bool enforce_single_leg_ghost{true};
  bool production_parking_replay{false};
};

// One executable production-router AOD batch.  ``original_members`` keeps the
// compact chromosome-phase audit payload, while ``legs``/``owners`` describe
// the actual physical movement after parking replay and an optional
// single-atom waypoint.  A waypoint therefore produces two consecutive
// batches with the same original member but distinct physical legs.
struct ExecutableBatch {
  std::vector<std::size_t> original_members;
  std::vector<Leg> legs;
  std::vector<std::int64_t> owners;
};

struct FitnessResult {
  std::vector<std::int64_t> chromosome;
  bool feasible{true};
  double negative_log_fidelity{};
  double transfer_nll{};
  double idle_excitation_nll{};
  double coherence_nll{};
  std::size_t move_batches{};
  double move_time_us{};
  double total_distance_um{};
  std::int64_t idle_exposures{};
  std::size_t transfers{};
  std::vector<std::vector<std::vector<std::size_t>>> phase_batches;
  std::string error;
  // ABI7 per-atom coherence-idle increment generated by this candidate.
  std::vector<double> candidate_idle_time_us;
  // Native-only ABI7 scheduler handoff.  Bindings intentionally expose only
  // ``phase_batches``; the rich current scorer consumes these physical rows
  // before serialization so it cannot accidentally rescore endpoint batches.
  std::vector<std::vector<ExecutableBatch>> executable_phase_batches;
};

struct RankedEntanglingOption {
  double movement_cost{};
  std::size_t pair_index{};
  bool reversed{};
};

class ArchitectureSnapshot {
 public:
  ArchitectureSnapshot(std::size_t n_atoms, std::vector<Point> site_coordinates,
                       std::vector<std::int64_t> storage_site_ids = {},
                       std::vector<std::array<std::int64_t, 2>>
                           entangling_site_pairs = {});

  std::size_t n_atoms() const noexcept { return n_atoms_; }
  const std::vector<Point>& site_coordinates() const noexcept {
    return site_coordinates_;
  }
  const std::vector<std::int64_t>& storage_site_ids() const noexcept {
    return storage_site_ids_;
  }
  const std::vector<std::array<std::int64_t, 2>>&
  entangling_site_pairs() const noexcept {
    return entangling_site_pairs_;
  }
  const std::vector<std::int64_t>& storage_site_ids_by_distance(
      const Point& source) const;
  const std::vector<std::int64_t>& nearest_storage_site_ids(
      const Point& source, std::size_t limit) const;
  const std::vector<RankedEntanglingOption>& ranked_entangling_options(
      const Point& first, const Point& second) const;
  const std::vector<double>& entangling_endpoint_distances(
      const Point& source) const;

 private:
  std::size_t n_atoms_;
  std::vector<Point> site_coordinates_;
  std::vector<std::int64_t> storage_site_ids_;
  std::vector<std::int64_t> storage_site_ids_by_x_;
  std::vector<std::array<std::int64_t, 2>> entangling_site_pairs_;
  mutable std::map<std::pair<double, double>, std::vector<std::int64_t>>
      storage_distance_cache_;
  mutable std::map<std::tuple<double, double, std::size_t>,
                   std::vector<std::int64_t>>
      nearest_storage_cache_;
  mutable std::map<std::tuple<double, double, double, double>,
                   std::vector<RankedEntanglingOption>>
      entangling_rank_cache_;
  mutable std::map<std::pair<double, double>, std::vector<double>>
      entangling_endpoint_distance_cache_;
};

}  // namespace zac_native
