backend_params:
  base_set: default0
  nonretranspile_changes:
    geyser_dump_transpiled_qasm: [False]

benchmarks:
- name: algorithm
  type: ['bv']
  n_qubits: [14, 19, 30, 70]
- name: algorithm
  type: ['cat']
  n_qubits: [22, 35]
- name: algorithm
  type: ['dnn']
  n_qubits: [51]
- name: algorithm
  type: ['ghz']
  n_qubits: [23, 40, 78]
- name: algorithm
  type: ['ising']
  n_qubits: [42, 98]
- name: algorithm
  type: ['knn']
  n_qubits: [31]
- name: algorithm
  type: ['multiply']
  n_qubits: [13]
- name: algorithm
  type: ['qft']
  n_qubits: [18]
- name: algorithm
  type: ['seca']
  n_qubits: [11]
- name: algorithm
  type: ['swap_test']
  n_qubits: [25]
- name: algorithm
  type: ['wstate']
  n_qubits: [27]