#!/usr/bin/env python3
"""Derive explanatory figures from the fixed model and accepted circuit data."""
import argparse
import csv
from decimal import Decimal, localcontext
import hashlib
import json
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]
PROJECT = PAPER.parent
SOURCE = PROJECT / "ZAC_zzx/results/paper_zh_v2/fig6_mechanism.csv"


def derive_values(source=SOURCE):
    with Path(source).open(newline="", encoding="utf-8") as stream:
        rows = [r for r in csv.DictReader(stream)
                if r["dataset"] == "zac18" and r["circuit"] == "qft_n18_transpiled"]
    if len(rows) != 1:
        raise ValueError("Expected exactly one accepted QFT-18 mechanism row")
    row = rows[0]
    if row["baseline_method"] != "M1" or row["strict_paired"] != "True":
        raise ValueError("QFT-18 mechanism comparison must be the accepted ZAC pair")
    with localcontext() as context:
        context.prec = 40
        transfer, excitation = Decimal("0.999"), Decimal("0.9975")
        values = {
            "ArgumentTransferFidelity": str(transfer),
            "ArgumentExcitationFidelity": str(excitation),
            "ArgumentStayOneFactor": f"{excitation:.6f}",
            "ArgumentStayTwoFactor": f"{excitation**2:.6f}",
            "ArgumentRoundtripFactor": f"{transfer**4:.6f}",
            "ArgumentStayOneLoss": f"{-1000*excitation.ln():.6f}",
            "ArgumentStayTwoLoss": f"{-2000*excitation.ln():.6f}",
            "ArgumentRoundtripLoss": f"{-4000*transfer.ln():.6f}",
            "MechanismQFTBaseTransfers": row["Bstar_transfers"].split(".")[0],
            "MechanismQFTGATransfers": row["M4_transfers"].split(".")[0],
            "MechanismQFTTransferGain": row["M4_minus_Bstar_log_atom_transfer"],
            "MechanismQFTExcitationGain": row["M4_minus_Bstar_log_idle_excitation"],
            "MechanismQFTCoherenceGain": row["M4_minus_Bstar_log_coherence_linear"],
        }
        for component in ("Transfer", "Excitation", "Coherence"):
            key = f"MechanismQFT{component}Gain"
            values[f"{key}Rounded"] = f"{Decimal(values[key]):.4f}"
        # The illustrative factor must use the same per-transfer model as the
        # accepted QFT row; it is not a measured whole-candidate score.
        predicted = (Decimal(row["M4_transfers"]) - Decimal(row["Bstar_transfers"])) * transfer.ln()
        if abs(predicted - Decimal(values["MechanismQFTTransferGain"])) > Decimal("1e-10"):
            raise ValueError("Transfer factor disagrees with frozen loss decomposition")
        predicted_excitation = (Decimal(row["M4_idle_exposures"])
                                - Decimal(row["Bstar_idle_exposures"])) * excitation.ln()
        if abs(predicted_excitation - Decimal(values["MechanismQFTExcitationGain"])) > Decimal("1e-10"):
            raise ValueError("Excitation factor disagrees with frozen loss decomposition")
    return values


def outputs(source=SOURCE):
    values = derive_values(source)
    tex = "% Generated by writing/generate_argument_values.py; do not edit.\n"
    tex += "\n".join(rf"\newcommand{{\{key}}}{{{value}}}" for key, value in values.items()) + "\n"
    metadata = {
        "kind": "derived_presentation_not_new_experiment",
        "mechanism_source": "ZAC_zzx/results/paper_zh_v2/fig6_mechanism.csv",
        "source_sha256": hashlib.sha256(Path(source).read_bytes()).hexdigest(),
        "circuit": "qft_n18_transpiled", "baseline": "ZAC",
        "illustration": "One atom; feasible stay/roundtrip; transfer and excitation factors only; not full objective",
        "roundtrip_transfers": 4, "loss_plot_scale": 1000,
        "macros": values,
    }
    return {PAPER / "method_argument_values.tex": tex,
            PAPER / "paper_argument_values.json": json.dumps(metadata, ensure_ascii=False, indent=2) + "\n"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, text in outputs().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(path.name)
        else:
            path.write_text(text, encoding="utf-8")
    print(json.dumps({"status": "fail" if stale else "pass", "read_only": args.check,
                      "stale_files": stale}, ensure_ascii=False))
    return bool(stale)


if __name__ == "__main__":
    raise SystemExit(main())
